// Copies compiled ABIs into the web app as a typed `as const` module so wagmi
// gets full type inference without importing JSON at runtime.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const artifactsDir = path.join(here, "..", "artifacts", "contracts");
const outFile = path.join(here, "..", "..", "web", "src", "lib", "abi.ts");

function readAbi(relativePath) {
  const artifact = JSON.parse(
    fs.readFileSync(path.join(artifactsDir, relativePath), "utf8")
  );
  return artifact.abi;
}

const vaultAbi = readAbi("MidnightVault.sol/MidnightVault.json");
const factoryAbi = readAbi("MidnightFactory.sol/MidnightFactory.json");

const banner = `// AUTO-GENERATED by contracts/scripts/export-abi.mjs — do not edit by hand.
// Regenerate with: cd contracts && npm run compile && npm run sync-abi
`;

const body = `${banner}
export const midnightVaultAbi = ${JSON.stringify(vaultAbi, null, 2)} as const;

export const midnightFactoryAbi = ${JSON.stringify(factoryAbi, null, 2)} as const;
`;

fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(outFile, body);
console.log(`Wrote ${outFile}`);
